apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux-system
#- base/repo.yaml
#- base/metrics-server.yaml
#- base/cert-manager.yaml
#- base/cert-manager-issuers.yaml
#- base/monitoring.yaml
#- base/monitoring-config.yaml
#- base/logging.yaml
#- base/tempo.yaml
#- base/ingress-nginx.yaml
#- base/aws-load-balancer-controller.yaml
#- base/flagger.yaml
#- base/teleport.yaml

#patches:
#- path: overlay/cert-manager.yaml
#- path: overlay/cert-manager-issuers.yaml
#- path: overlay/monitoring.yaml
#- path: overlay/monitoring-logging.yaml
#- path: overlay/monitoring-tempo.yaml
#- path: overlay/logging.yaml
#- path: overlay/aws-load-balancer-controller.yaml
#- path: overlay/flagger.yaml
#- path: overlay/teleport.yaml

#patchesJson6902:
#- path: overlay/monitoring-tempo-ops.yaml
#  target:
#    group: helm.toolkit.fluxcd.io
#    version: v2beta1
#    kind: HelmRelease
#    name: monitoring
#    namespace: flux-system
