apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager-config
      sourceRef:
        kind: HelmRepository
        name: getupcloud
      version: ~> 0.2
  dependsOn:
    - name: cert-manager
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: cert-manager-config
  storageNamespace: cert-manager
  targetNamespace: cert-manager
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  values:
    # acme_email: account@example.com
    cluster_issuer_dns01:
      aws_access_key_id: ""
      aws_region: ""
      aws_zones: ""
      enabled: false
    cluster_issuer_letsencrypt:
      enabled: true
    cluster_issuer_selfsigned:
      enabled: true
    ingress_class: nginx
