apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: "~> 0.49.0"
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 10m
  releaseName: otel-operator
  storageNamespace: otel-system
  targetNamespace: otel-system
  values:
    replicaCount: 2
    pdb:
      create: true
    manager:
      extraArgs:
      - --enable-multi-instrumentation
    admissionWebhooks:
      certManager:
        enabled: true
        issuerRef:
          kind: ClusterIssuer
          name: selfsigned
      autoGenerateCert:
        enabled: false
