apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  values:
    clusterName: #output:{cluster_name}

    replicaCount: 1

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: #output:{aws_load_balancer_controller_iam_role_arn}
