apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: #output:{aws_eso_iam_role_arn}
