apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  values:
    clusterName: ${CLUSTER_NAME}

    replicaCount: 1

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "${AWS_ALB_ROLE_ARN}"
