apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  values:
    template-store:
      metadata:
        name: #output:{cluster_name}
      spec:
        provider:
          aws:
            region: #output:{aws_region}
