apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  values:
    templates:
      spec:
        provider:
          aws:
            #region: #aws_region#
