apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  values:
    # acme_email: account@example.com
    # cluster_issuer_dns01:
    #   aws_access_key_id: ""
    #   aws_region: ""
    #   aws_zones: ""
    #   enabled: false
