apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  values:
    serviceAccount:
      annotations:
        #eks.amazonaws.com/role-arn: "#cert_manager_iam_role_arn#"

