apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
spec:
  values:
    #secret:
    #  namespaceLabelSelector:
    #    ecr-credentials: "true"

    awsAccountId: #output:"{overlay["ecr_credentials_sync_aws_account_id"]}"

    aws_credentials:
      aws_access_key_id: #output:{overlay["ecr_credentials_sync_aws_access_key_id"]}
      aws_secret_access_key: #output:{overlay["ecr_credentials_sync_aws_secret_access_key"]}


    ecr:
      region: #output:{overlay["ecr_credentials_sync_aws_region"]}
