apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
spec:
  values:
    #secret:
    #  namespaceLabelSelector:
    #    ecr-credentials: "true"

    awsAccountId: #output:"{overlay["ecr_credentials_sync_aws_account_id"]}"

    ecr:
      region: #output:{overlay["ecr_credentials_sync_aws_region"]}
