apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
spec:
  values:
    #secret:
    #  namespaceLabelSelector:
    #    ecr-credentials: "true"

    #awsAccountId: #aws_account_id#

    ecr:
      #region: "#ecr_credential_sync_region#"

    serviceAccount:
      create: true
      name: "ecr-credentials-sync"
      #roleArn: #ecr_credential_sync_iam_role_arn#
