apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  values:
    #domainFilters:
    #- example.com
    #- example.dev.br

    #excludeDomains:
    #- exemplo.com.br
