apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  values:
    loki:
      storage:
        type: s3
        s3:
          region: #output:{region}
        bucketNames:
          chunks: #output:{loki_bucket_name}
          ruler: #output:{loki_bucket_name}
