apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  values:
    serviceAccount:
      annotations:
        #eks.amazonaws.com/role-arn: "#loki_iam_role_arn#"
    loki:
      storage:
        type: s3
        s3:
          #region: "#aws_region#"
        bucketNames:
          #chunks: "#loki_s3_bucket_name#"
          #ruler: "#loki_s3_bucket_name#"
