apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  values:
    ###############################################
    alertmanager:
      config:
        route:
          #################################################################
          ## Routes
          #################################################################
          routes:
          # watchdog aims to test the alerting pipeline
          - matchers:
            - alertname = Watchdog
            continue: false

          # Ignore following alerts and/or namespaces
          - receiver: blackhole
            matchers:
            - alertname = CPUThrottlingHigh
              #namespace =~ logging|monitoring|ingress-nginx|velero|cert-manager|getup|.*-(controllers?|operators?|provisioners?|system)
            continue: false

          - receiver: blackhole
            matchers:
            - alertname = KubeJobFailed
            - namespace = zora-system
            continue: false

          #############################
          # Cronitor
          #############################
          #- receiver: cronitor
          #  matchers:
          #  - alertname = CronitorWatchdog
          #  group_wait: 1s
          #  group_interval: 10s
          #  continue: false

          #############################
          # Slack
          #############################
          #- receiver: slack
          #  matchers:
          #  - alertname != ""
          #  continue: true

          #############################
          # MS Teams
          #############################
          #- receiver: msteams
          #  matchers:
          #  - alertname != ""
          #  continue: true

          #############################
          # PageDuty
          #############################
          #- receiver: pagerduty
          #  matchers:
          #  - alertname != ""
          #  - severity: critical
          #  continue: true

          #############################
          # Opsgenie
          #############################
          #- receiver: opsgenie
          #  matchers:
          #  - alertname =~ KubeNodeUnreachable|KubeCronJobRunning|KubeDaemonSetRolloutStuck|KubePodCrashLooping|KubePodNotReady|KubeStatefulSetGenerationMismatch|KubeStatefulSetReplicasMismatch
          #  - namespace =~ logging|monitoring|velero|cert-manager|getup|.*-(ingress|controllers?|operators?|provisioners?|system)
          #  - severity = warning
          #  continue: true
          #
          #- receiver: opsgenie
          #  matchers:
          #  - alertname =~ KubeDeploymentGenerationMismatch|KubeDeploymentReplicasMismatch|KubeNodeNotReady|KubeAPILatencyHigh|KubeStatefulSetUpdateNotRolledOut|KubeJobCompletion|KubeJobFailed
          #  - namespace =~ logging|monitoring|velero|cert-manager|getup|.*-(ingress|controllers?|operators?|provisioners?|system)
          #  - severity = warning
          #  continue: true
          #
          #- receiver: opsgenie
          #  matchers:
          #  - alertname =~ CertificateAlert|KubeClientCertificateExpiration|ClockSkewDetected|EndpointDown|HighNumberOfFailedProposals|HighNumberOfFailedHTTPRequests
          #  - namespace =~ logging|monitoring|velero|cert-manager|getup|.*-(ingress|controllers?|operators?|provisioners?|system)
          #  - severity = warning
          #  continue: true
          #
          #- receiver: opsgenie
          #  matchers:
          #  - alertname =~ AlertmanagerFailedReload|PrometheusOperatorReconcileErrors|PrometheusConfigReloadFailed|PrometheusNotConnectedToAlertmanagers|PrometheusTSDBReloadsFailing|PrometheusTSDBCompactionsFailing|PrometheusTSDBWALCorruptions|PrometheusNotIngestingSamples
          #  - namespace = monitoring
          #  - severity = warning
          #  continue: true
          #
          #- receiver: opsgenie
          #  matchers:
          #  - severity = critical
          #  continue: true

          # ignore non-matching alerts. This is mostly for metrics purpose.
          - receiver: blackhole
            matchers:
            - alertname != ""
            continue: false

        #################################################################
        ## Receivers
        ##
        ## SLA must obey the following rules:
        ##
        ## high: prod/homolog/preprod
        ##  low: dev/test
        ## none: no-ops
        #################################################################

        receivers:
        # does nothing
        - name: blackhole

        #############################
        # Cronitor
        #############################
        #- name: cronitor
        #  webhook_configs:
        #  - url: #output:{overlay["cronitor_ping_url"]}
        #    send_resolved: false

        #############################
        # Slack
        #############################
        #- name: slack
        #  slack_configs:
        #  - send_resolved: true
        #    api_url: #output:{overlay["slack_api_url"]}
        #    channel: #output:{overlay["slack_channel"]}
        #    color: |-
        #      {{- if eq .Status "firing" -}}
        #        {{- if eq (index .Alerts 0).Labels.severity "critical" -}}
        #          #FF2222
        #        {{- end -}}
        #        {{- if eq (index .Alerts 0).Labels.severity "warning" -}}
        #          #FF8800
        #        {{- end -}}
        #        {{- if and (ne (index .Alerts 0).Labels.severity "critical") (ne (index .Alerts 0).Labels.severity "warning") -}}
        #          #22FF22
        #        {{- end -}}
        #      {{- else -}}
        #        #22FF22
        #      {{- end -}}
        #    title: '{{ template "slack.default.title" . }}'
        #    pretext: '{{ .CommonAnnotations.summary }}'
        #    fallback: '{{ template "slack.default.fallback" . }}'
        #    text: |-
        #      {{ range .Alerts -}}
        #      *Severity:* `{{ .Labels.severity | title }}` (<{{ .GeneratorURL }}|graph>)
        #      *Description:* {{ .Annotations.message }}
        #      *Labels:*{{ range .Labels.SortedPairs }} `{{ .Name }}={{ .Value }}`{{ end }}
        #      {{ end }}

        #############################
        # MSTeams
        #############################
        #- name: msteams
        #  webhook_configs:
        #  - url: #output:{overlay["msteams_channel_url"]}

        #############################
        # Opsgenie
        #############################
        #- name: opsgenie
        #  opsgenie_configs:
        #  - api_key: #output:{overlay["opsgenie_integration_api_key"]}
        #    tags: #output:{customer_name}, {cluster_name}, {cluster_provider}, {cluster_sla}
        #    # Choose priority according to SLA: high=[P1|P2], low=[P3|P4|P5]
        #    priority: P1

        #############################
        # PagerDuty
        #############################
        #- name: pagerduty
        #  pagerduty_configs:
        #  - service_key: #output:{overlay["pagerduty_service_key"]}
        #    group: #output:sla-{cluster_sla}
