apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  values:
    ###############################################
    prometheus:
      prometheusSpec:
        enableRemoteWriteReceiver: true
        remoteWriteDashboards: true

    ###############################################
    grafana:
      sidecar:
        datasources:
          exemplarTraceIdDestinations:
            datasourceUid: tempo
            traceIdLabelName: traceID

      grafana.ini:
        feature_toggles:
          traceToMetrics: true
