apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  values:
    ###############################################
    alertmanager:
      config:
        route:
          #################################################################
          ## Routes
          #################################################################
          routes:
          # watchdog aims to test the alerting pipeline
          - match:
              alertname: Watchdog
            continue: false

          # Ignore following alerts and/or namespaces
          - receiver: blackhole
            match_re:
              alertname: "^(CPUThrottlingHigh)$"
              namespace: "^(logging|monitoring|velero|cert-manager|getup)$|.*-(ingress|controllers?|operators?|provisioners?|system)$"
            continue: false

          #############################
          # Cronitor
          #############################
          #- receiver: cronitor
          #  match:
          #    alertname: CronitorWatchdog
          #  group_wait: 5s
          #  group_interval: 1m
          #  continue: false

          #############################
          # Slack
          #############################
          #- receiver: slack
          #  match_re:
          #    alertname: .*
          #  continue: true

          #############################
          # MS Teams
          #############################
          #- receiver: msteams
          #  match_re:
          #   alertname: .*
          #  continue: true

          #############################
          # Opsgenie
          #############################
          #- receiver: opsgenie
          #  match_re:
          #    alertname: (KubeCronJobRunning|KubeDaemonSetRolloutStuck|KubeDeploymentGenerationMismatch|KubeDeploymentReplicasMismatch|KubePodCrashLooping|KubePodNotReady|KubeStatefulSetGenerationMismatch|KubeStatefulSetReplicasMismatch|KubeCronJobRunning|KubeDaemonSetRolloutStuck|KubeDeploymentGenerationMismatch|KubeDeploymentReplicasMismatch|KubePodCrashLooping|KubePodNotReady|KubeStatefulSetGenerationMismatch|KubeStatefulSetReplicasMismatch|AlertmanagerFailedReload|CertificateAlert|ClockSkewDetected|EndpointDown|HighNumberOfFailedProposals|PrometheusOperatorReconcileErrors|PrometheusConfigReloadFailed|PrometheusNotConnectedToAlertmanagers|PrometheusTSDBReloadsFailing|PrometheusTSDBCompactionsFailing|PrometheusTSDBWALCorruptions|PrometheusNotIngestingSamples|KubeNodeUnreachable|KubeClientCertificateExpiration|KubeNodeNotReady|KubeAPILatencyHigh|HighNumberOfFailedHTTPRequests|KubeStatefulSetUpdateNotRolledOut|KubeJobCompletion|KubeJobFailed)
          #    namespace: "^(logging|monitoring|velero|cert-manager|getup)$|.*-(ingress|controllers?|operators?|provisioners?|system)$"
          #    severity: warning # treat these warnings as if the where critical
          #  continue: true
          #- receiver: opsgenie
          #  match:
          #    severity: critical
          #  continue: true

          #############################
          # PageDuty
          #############################
          #- receiver: pagerduty
          #  match_re:
          #    alertname: (KubeCronJobRunning|KubeDaemonSetRolloutStuck|KubeDeploymentGenerationMismatch|KubeDeploymentReplicasMismatch|KubePodCrashLooping|KubePodNotReady|KubeStatefulSetGenerationMismatch|KubeStatefulSetReplicasMismatch|KubeCronJobRunning|KubeDaemonSetRolloutStuck|KubeDeploymentGenerationMismatch|KubeDeploymentReplicasMismatch|KubePodCrashLooping|KubePodNotReady|KubeStatefulSetGenerationMismatch|KubeStatefulSetReplicasMismatch|AlertmanagerFailedReload|CertificateAlert|ClockSkewDetected|EndpointDown|HighNumberOfFailedProposals|PrometheusOperatorReconcileErrors|PrometheusConfigReloadFailed|PrometheusNotConnectedToAlertmanagers|PrometheusTSDBReloadsFailing|PrometheusTSDBCompactionsFailing|PrometheusTSDBWALCorruptions|PrometheusNotIngestingSamples|KubeNodeUnreachable|KubeClientCertificateExpiration|KubeNodeNotReady|KubeAPILatencyHigh|HighNumberOfFailedHTTPRequests|KubeStatefulSetUpdateNotRolledOut|KubeJobCompletion|KubeJobFailed)
          #    namespace: "^(logging|monitoring|velero|cert-manager|getup)$|.*-(ingress|controllers?|operators?|provisioners?|system)$"
          #    severity: warning # treat these warnings as if the where critical
          #  continue: true
          #- receiver: pagerduty
          #  match:
          #    severity: critical
          #  continue: true

          # ignore non-matching alerts. This is mostly for metrics purpose.
          - receiver: blackhole
            match_re:
              alertname: .*
            continue: false

        #################################################################
        ## Receivers
        ##
        ## SLA must obey the following rules:
        ##
        ## high: prod/homolog/preprod
        ##  low: dev/test
        ## none: no-ops
        #################################################################

        receivers:
        # does nothing
        - name: blackhole

        #############################
        # Cronitor
        #############################
        #- name: cronitor
        #  webhook_configs:
        #  #- url: #cronitor_ping_url#
        #    send_resolved: false

        #############################
        # Slack
        #############################
        #- name: slack
        #  slack_configs:
        #  - send_resolved: true
        #    #api_url: #slack_api_url#
        #    #channel: "#slack_channel#"
        #    color: |-
        #      {{- if eq .Status "firing" -}}
        #        {{- if eq (index .Alerts 0).Labels.severity "critical" -}}
        #          #FF2222
        #        {{- end -}}
        #        {{- if eq (index .Alerts 0).Labels.severity "warning" -}}
        #          #FF8800
        #        {{- end -}}
        #        {{- if and (ne (index .Alerts 0).Labels.severity "critical") (ne (index .Alerts 0).Labels.severity "warning") -}}
        #          #22FF22
        #        {{- end -}}
        #      {{- else -}}
        #        #22FF22
        #      {{- end -}}
        #    title: '{{ template "slack.default.title" . }}'
        #    pretext: '{{ .CommonAnnotations.summary }}'
        #    fallback: '{{ template "slack.default.fallback" . }}'
        #    text: |-
        #      {{ range .Alerts -}}
        #      *Severity:* `{{ .Labels.severity | title }}` (<{{ .GeneratorURL }}|graph>)
        #      *Description:* {{ .Annotations.message }}
        #      *Labels:*{{ range .Labels.SortedPairs }} `{{ .Name }}={{ .Value }}`{{ end }}
        #      {{ end }}

        #############################
        # MSTeams
        #############################
        #- name: msteams
        #  webhook_configs:
        #  #- url: #msteams_channel_url#

        #############################
        # Opsgenie
        #############################
        #- name: opsgenie
        #  opsgenie_configs:
        #  #- api_key: #opsgenie_integration_api_key#
        #    #tags: #customer_name#, #cluster_name#, #cluster_provider#, #cluster_sla#
        #    # Choose priority according to SLA: high=[P1|P2], low=[P3|P4|P5]
        #    priority: P1

        #############################
        # PagerDuty
        #############################
        #- name: pagerduty
        #  pagerduty_configs:
        #  #- service_key: #pagerduty_service_key#
        #    #group: sla-#cluster_sla#
