apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  values:
    ###############################################
    grafana:
      #######################################
      additionalDataSources:
      - name: Loki
        type: loki
        uid: loki
        editable: true
        url: http://loki-gateway.logging.svc.cluster.local.:80
        basicAuth: false
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 5000
          manageAlerts: false
          timeout: 120
          derivedFields:
          - datasourceUid: tempo
            matcherRegex: "traceID=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"
