apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  values:
    opencost:
      customPricing:
        provider: custom
        costModel:
          description: Custom prices for DigitalOcean
          CPU: 0.2
          RAM: 0.5
          storage: 0.3
      exporter:
        defaultClusterId: #output:{cluster_name}
        persistence:
          storageClass: #output:{default_storage_class_name}
