apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  values:
    opencost:
      customPricing:
        costModel:
          awsSpotDataRegion: #output:{aws_region}
          awsSpotDataBucket: #output:{overlay["opencost_spot_datafeed_bucket_name"]}
          awsSpotDataPrefix: #output:{overlay["opencost_spot_datafeed_bucket_prefix"]}
          projectID: #output:"{aws_account_id}"
      exporter:
        defaultClusterId: #output:{cluster_name}
        persistence:
          storageClass: #output:{overlay["opencost_storage_class_name"]}
    serviceAccount:
      name: opencost
      annotations:
        eks.amazonaws.com/role-arn: #output:{overlay["opencost_iam_role_arn"]}
