apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: flux-system
spec:
  values:
    admissionWebhooks:
      certManager:
        enabled: false
      autoGenerateCert:
        enabled: true
