apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  values:
    tempo:
      storage:
        trace:
          s3:
            bucket: #output:{tempo_bucket_name}
            region: #output:{region}
            endpoint: #output:{region}.digitaloceanspaces.com
            access_key: #output:{tempo_access_key}
            secret_key: #output:{tempo_secret_key}

