apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  values:
    initContainers:
    - name: velero-velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.12.0
      volumeMounts:
      - mountPath: /target
        name: plugins
    - name: digitalocean-velero-plugin
      image: digitalocean/velero-plugin:v1.1.0
      volumeMounts:
      - mountPath: /target
        name: plugins

    configuration:
      extraEnvVars:
        DIGITALOCEAN_TOKEN: #output:{overlay["velero_do_token"]}

      defaultBackupStorageLocation:
      - aws: default
      backupStorageLocation:
      - provider: aws
        name: default
        default: true
        prefix: #output:velero/{cluster_name}-{region}
        bucket: #output:{velero_bucket_name}
        config:
          region: #output:{region}
          s3Url: #output:https://{region}.digitaloceanspaces.com

      volumeSnapshotLocation:
      - provider: digitalocean.com/velero
        name: default
        default: true
        config:
          region: #output:{region}

    credentials:
      secretContents:
        cloud: |+
          [default]
          aws_access_key_id=#output:{velero_access_key}
          aws_secret_access_key=#output:{velero_secret_key}
