apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  values:
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.0
      volumeMounts:
      - mountPath: /target
        name: plugins

    configuration:
      extraEnvVars:
        DIGITALOCEAN_TOKEN: #output:{velero_do_token}

      defaultBackupStorageLocation:
      - aws: default
      backupStorageLocation:
      - provider: aws
        name: default
        default: true
        prefix: #output:velero/{cluster_name}-{region}
        bucket: #output:{velero_s3_bucket_name}
        config:
          region: #output:{region}

      defaultVolumeSnapshotLocations:
      - aws: default
      volumeSnapshotLocation:
      - provider: aws
        name: default
        default: true
        config:
          region: #output:{region}

    schedules:
      volumes:
        schedule: '0 3 * * *'
        template:
          storageLocation: default
          ttl: 168h0m0s

          # Please note labelSelector can't be empty
          # https://github.com/vmware-tanzu/velero/issues/2083
          #labelSelector:
          #  app: web

          includedClusterScopedResources:
          - persistentvolumes
          - persistentvolumeclaims
          excludedNamespaces:
          - kube-system
          - kube-public
          - velero
          - monitoring
          - logging

          snapshotVolumes: true
          volumeSnapshotLocations:
          - default

      resources:
        schedule: '0 */12 * * *'
        template:
          storageLocation: default
          ttl: 720h0m0s

          # Please note labelSelector can't be empty
          # https://github.com/vmware-tanzu/velero/issues/2083
          #labelSelector:
          #  app: web

          includedNamespaces:
          - "*"
          excludedNamespaces:
          - kube-system
          - kube-public
          - monitoring
          - velero
          includedResources:
          - "*"
          #excludedResources: []
          includeClusterResources: true

          snapshotVolumes: false
